#!/usr/bin/env bash

# autor: Gabriel-Tapes
# descrição: script para compilar e rodar programas em Fortran 95
# version: 1.1

nome_do_arquivo=$1

if [ -a ./$nome_do_arquivo.f95 ]
then
   msg=$(f95 $nome_do_arquivo.f95 -o exe/$nome_do_arquivo)
   
   if [ -z  $msg ]
   then
      ./exe/$nome_do_arquivo
   else
      echo $msg
   fi

else
   echo "Nome de arquivo invalido!"
fi
